FROM "reisners/bpy:master"

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY Mod/Pyramids-and-Polyhedrons /root/.FreeCAD/Mod/Pyramids-and-Polyhedrons

EXPOSE 3000

WORKDIR /work
