FROM amrit3701/freecad-cli:latest

RUN apt update \
    && apt install -y apt-utils \
    && apt install -y software-properties-common \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1 \
    && apt install -y sudo \
    && apt install -y git \
    && apt install -y llvm

ADD blender-as-python-module/install /install
RUN /install

ADD blender-as-python-module/build /build
RUN /build

ENV PYTHONPATH=/usr/lib/python3.8/site-packages
