#!/bin/bash

cd /blender-git/blender

export BUILD_CMAKE_ARGS="-DWITH_MOD_OCEANSIM=OFF -DWITH_OIDN=OFF -DPYTHON_SITE_PACKAGES=/usr/lib/python3.7/site-packages"

#sudo BUILD_CMAKE_ARGS=${BUILD_CMAKE_ARGS} make bpy
make bpy
