#!/bin/bash

set -o xtrace
set -o errexit

cd /source/blender

export BUILD_CMAKE_ARGS="\
-DWITH_MEM_JEMALLOC=OFF \
-DWITH_MOD_OCEANSIM=OFF \
-DWITH_OIDN=OFF \
-DWITH_INSTALL_PORTABLE=OFF \
-DWITH_PYTHON_INSTALL=OFF \
-DWITH_AUDASPACE=OFF \
-DWITH_OPENCOLORIO=ON \
-DWITH_PYTHON_MODULE=ON \
-DPYTHON_SITE_PACKAGES=${PYTHON_SITE_PACKAGES}\
"

make bpy

echo +++ make bpy finished +++
find /source -type d

cd /source/build_linux_bpy
echo running make install in /build_linux_bpy with PYTHON_SITE_PACKAGES=${PYTHON_SITE_PACKAGES}...
make install

echo +++ make install finished +++
